[package]
name = "elysium"
version = "1.0.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
image = { version = "0", default-features = false, features = ["png"] }
rustfft = "6"
windows-capture = "2"
windows = { version = "0", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_UI_Shell", "Win32_Graphics_Gdi", "Win32_Graphics_Dwm"] }
serde_json = "1"
vigem-client = "0"
rhai = { version = "1", features = ["sync"] }
ratatui = "0"
windows-link = { version = "0", optional = true }

[[bin]]
name = "obs64"
path = "src/main.rs"

[features]
default = ["dna", "nte"]
dna = []
nte = ["ocr"]
ocr = ["dep:windows-link"]

[profile.release]
strip = true
lto = true
codegen-units = 1

[profile.dev]
opt-level = 3
