// {
//   "author": "",
//   "desc": "探索指南+环期赏令",
//   "loop": false,
//   "timeout": 90
// }

click(LB);
press(LB);
rstick(0, 20000, 0.1);
rstick(0, 0, 0.1);
release(LB);
press(RIGHT, 0.8);
release(RIGHT);
click(LEFT);
click(A, 0.1, 0.6);
click(DOWN);
click(A);
click(RIGHT);
click(DOWN);
click(A, 0.1, 1.5);
click(A);
click(A, 0.1, 1.5);
click(B);
click(B, 0.1, 1.1);
click(B, 0.1, 0.6);
click(B, 0.1, 0.6);

click(RIGHT);
click(RIGHT);
click(RIGHT);
click(A, 0.1, 0.6);
click(DOWN);
click(Y, 0.1, 1.5);
click(B);
click(B, 0.1, 0.6);
click(B, 0.1, 0.6);
click(B, 0.1, 0.6);
