name: build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: full
            archive: elysium-full.7z
            cargo_args: ""
            files: "*.exe dna nte *.md user*"
          - name: dna
            archive: elysium-dna.7z
            cargo_args: "--no-default-features --features dna"
            files: "*.exe dna *.md user-dna-scripts"
          - name: nte
            archive: elysium-nte.7z
            cargo_args: "--no-default-features --features nte"
            files: "*.exe nte *.md user-nte-scripts"

    steps:
    - name: Prepare
      run: git config --global core.autocrlf false
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - name: Setup UPX
      uses: crazy-max/ghaction-upx@v4
      with:
        install-only: true
        version: latest
    - name: Compile
      run: |
        curl -OL https://github.com/nyfair/elysium/releases/download/latest/mnn_bindings.7z
        7z x mnn_bindings.7z -o"rust-paddle-ocr" -aoa
        rustup set profile minimal
        rustup update
        cargo build --release ${{ matrix.cargo_args }}
        move target\release\*.exe .
        upx --ultra-brute *.exe
        7z a ${{ matrix.archive }} ${{ matrix.files }}

    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.archive }}
        tag: latest
        overwrite: true
