name: build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Prepare
      run: git config --global core.autocrlf false
    - uses: actions/checkout@v6
    - name: Setup UPX
      uses: crazy-max/ghaction-upx@v4
      with:
        install-only: true
        version: latest
    - name: Compile
      run: |
        rustup set profile minimal
        rustup update
        cargo build --release
        move target\release\*.exe .
        upx --ultra-brute *.exe
        7z a elysium.7z *.exe dna nte *.md
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: elysium.7z
        tag: latest
        overwrite: true
        file_glob: true
